services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        environment:
            APP_ENV: local
            APP_DEBUG: true
            DB_CONNECTION: pgsql
            DB_HOST: db
            DB_PORT: 5432
            DB_DATABASE: laravel
            DB_USERNAME: laravel_user
            DB_PASSWORD: secret
        depends_on:
            - db

    db:
        image: postgres:15
        container_name: laravel_db
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: laravel_user
            POSTGRES_PASSWORD: secret
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"

volumes:
    pgdata:
